# main.py

import json
import os
from agents.financial_agent import run as financial_run
from agents.market_agent import run as market_run
from agents.sentiment_agent import run as sentiment_run
from agents.validator_agent import ValidatorAgent
from agents.debate_agent import DebateAgent
from agents.mediator_agent import run_mediator
from utils.display import print_logic_path
from utils.thresholds import (
    DEFAULT_CONFLICT_ALPHA,
    DEFAULT_CONFLICT_THRESHOLD,
    SIGNAL_NEUTRAL_BAND,
    SIGNAL_STRONG_INTENSITY_FLOOR,
)


def main():
    print("=" * 60)
    print("🚀 KÍCH HOẠT HỆ THỐNG PHÂN TÍCH TÀI CHÍNH MULTI-AGENT CRYPTO")
    print("=" * 60)

    # Step 1: Gather independent opinions from Specialist Agents
    print("\n[Step 1] Thu thập nhận định độc lập từ các Specialist Agents...")
    try:
        financial_output = financial_run()
        print(f"  - Financial Agent: {financial_output['signal']} (Confidence: {financial_output['confidence']})")
        print_logic_path("initial", financial_output.get("logic_path"))
    except Exception as e:
        import traceback
        traceback.print_exc()
        financial_output = None

    try:
        market_output = market_run()
        print(f"  - Market Agent: {market_output['signal']} (Confidence: {market_output['confidence']})")
        print_logic_path("initial", market_output.get("logic_path"))
    except Exception as e:
        print(f"  - ERROR Market Agent: {e}")
        market_output = None

    try:
        sentiment_output = sentiment_run()
        print(f"  - Sentiment Agent: {sentiment_output['signal']} (Confidence: {sentiment_output['confidence']})")
        print_logic_path("initial", sentiment_output.get("logic_path"))
    except Exception as e:
        print(f"  - ERROR Sentiment Agent: {e}")
        sentiment_output = None

    named_outputs = [
        ("Financial_Agent", financial_output),
        ("Market_Agent", market_output),
        ("Sentiment_Agent", sentiment_output),
    ]
    all_outputs = [o for _, o in named_outputs if o is not None]
    missing_agents = [name for name, o in named_outputs if o is None]

    if not all_outputs:
        print("\n[!] Cả 3 Specialist Agent đều thất bại; xem lỗi từng agent ở trên.")
        print("    Tự động kích hoạt cơ chế dự phòng: Tải dữ liệu từ 'outputs/logs.json'...")
        try:
            with open("outputs/logs.json", "r", encoding="utf-8") as f:
                all_outputs = json.load(f)
            missing_agents = []  # dữ liệu dự phòng thay thế toàn bộ live outputs
            print("    [✓] Đã tải thành công dữ liệu dự phòng từ logs.json.")
        except Exception as e:
            print(f"    [✗] Lỗi tải dữ liệu dự phòng: {e}")
            print("\n[FATAL] Không thu thập được đầu ra từ bất kỳ Agent nào. Dừng pipeline.")
            return

    if financial_output or market_output or sentiment_output:
        os.makedirs("outputs", exist_ok=True)
        with open("outputs/logs.json", "w", encoding="utf-8") as f:
            json.dump(all_outputs, f, indent=2, ensure_ascii=False)
        print("  -> Đã lưu thô outputs của 3 Agent vào 'outputs/logs.json'")

    # Step 4: Run Validator Agent
    print("\n[Step 4] Khởi chạy Validator Agent thẩm định mâu thuẫn hệ thống...")
    validator = ValidatorAgent(alpha=DEFAULT_CONFLICT_ALPHA, threshold=DEFAULT_CONFLICT_THRESHOLD, use_llm=True)
    validation_result = validator.evaluate_pipeline(all_outputs, missing_agents=missing_agents)

    if not validation_result.get("explanations_valid", True):
        print("\n[!] RCA/Debate có giải thích chưa đạt kiểm tra nguồn. "
              "Các cập nhật bị từ chối đã giữ trạng thái cũ; lần chạy này không phải pipeline đầy đủ hợp lệ.")

    if validation_result.get("degraded_mode"):
        print(
            f"\n[⚠ CẢNH BÁO] Đang chạy ở chế độ suy giảm (degraded mode): "
            f"thiếu {len(missing_agents)}/3 agent ({', '.join(missing_agents) or 'không rõ'}). "
            f"Kết quả bên dưới KHÔNG đại diện đầy đủ cho sự đồng thuận 3-agent."
        )

    # If the validator already performed a debate, its results are stored in 'debate_updated_outputs'
    debate_outputs = validation_result.get('debate_updated_outputs')
    if debate_outputs:
        print("\n[Debate Results] (generated by ValidatorAgent):")
        for out in debate_outputs:
            print(f"Agent {out['agent_id']} final confidence: {out['confidence']:.3f}")
        final_outputs = debate_outputs
    else:
        final_outputs = all_outputs

    # Display validation metrics
    print("\n[KẾT QUẢ KIỂM ĐỊNH TOÁN HỌC & LOGIC]:")
    print(f"  - Chỉ số mâu thuẫn lai (Conflict Score): {validation_result['conflict_score']}")
    print(f"  - Sai biệt phân phối (Mean Pairwise KL): {validation_result['metrics']['mean_pairwise_kl']}")
    print(f"  - Phương sai quyết định (Decision Variance): {validation_result['metrics']['decision_variance']}")
    print(f"  - Phát hiện mâu thuẫn vượt ngưỡng (Conflict Detected): {validation_result['conflict_detected']}")
    print(f"  - Phân loại loại hình mâu thuẫn (Conflict Categories): {validation_result['conflict_categories']}")
    print(f"  - Kích hoạt Debate Module (Trigger Debate): {validation_result['trigger_debate_module']}")

    # Step 5: Aggregate signals using Mediator Agent
    print("\n[Step 5] Chạy Mediator Agent để hợp nhất tín hiệu...")
    mediator_result = run_mediator(final_outputs)
    score = mediator_result['S_final']
    if len(final_outputs) < 2:
        # Chỉ còn 1 (hoặc 0) specialist — S_final lúc này chỉ phản ánh ý kiến
        # của một agent, không phải kết quả hợp nhất đa-agent. Không nên gán
        # nhãn BUY/SELL như thể đó là quyết định đã qua đối chiếu chéo.
        intensity = "N/A"
        signal = "INSUFFICIENT_DATA"
    else:
        intensity = "STRONG" if abs(score) > SIGNAL_STRONG_INTENSITY_FLOOR else "WEAK"
        signal = (
            "BUY" if score > SIGNAL_NEUTRAL_BAND
            else ("SELL" if score < -SIGNAL_NEUTRAL_BAND else "NEUTRAL")
        )

    print(f"  - S_final: {score:.4f} | Intensity: {intensity} | Signal: {signal}")    # Save mediator result
    with open("outputs/mediator_result.json", "w", encoding="utf-8") as f:
        json.dump(mediator_result, f, indent=2, ensure_ascii=False)
    print("  -> Mediator result saved to 'outputs/mediator_result.json'")

    print("\n[BÁO CÁO PHÂN TÍCH NGUYÊN NHÂN RỄ CỐT - RCA REPORT]:")
    print("-" * 60)
    print(validation_result['root_cause_analysis'])
    print("-" * 60)

    # Step 4: Save validation report for visualization
    with open("outputs/validation_report.json", "w", encoding="utf-8") as f:
        json.dump(validation_result, f, indent=2, ensure_ascii=False)
    print("\n  -> Báo cáo thẩm định chi tiết đã được lưu vào 'outputs/validation_report.json'")
    print("=" * 60)

if __name__ == "__main__":
    main()
